version: '3'
services:
  react:
    restart: always
    build: ./front-end
    ports:
      - 3000:3000
    depends_on:
      - node
      - mongo
  node:
    restart: always
    environment:
      - HOST=mongo
    build: ./back-end
    ports:
      - 3001:3001
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: